Test with checkmate's blocklist in view_pdf
hypothesis/via3 pull request #322
Opened 2021-01-27 11:37 UTC by marcospri

Added the checkmatelib dependency and did the checkmate test in direclty in the view.

Quick local testing, with `main` in checkmate's repo:

Blocked url `http://0.0.0.0:9082/pdf?url=42.228.75.1%2Fbin.sh`

vs

`http://0.0.0.0:9082/pdf?url=http%3A%2F%2Fwww.africau.edu%2Fimages%2Fdefault%2Fsample.pdf`

2021-01-27 11:41 UTC, marcospri commented on via/views/view_pdf.py
> +        logging.exception("Failed to check url against checkmate with error: %s", err)
I think it makes sense to log the exception but allow the request to continue at least now that via3 is a different service than via

2021-01-27 11:45 UTC, marcospri commented on via/views/view_pdf.py
> +    checkmate = CheckmateClient(request.registry.settings["checkmate_url"])
I just dropped all of this here in the view but maybe there's a better pyramid mechanism I could use.

I'd say https://github.com/hypothesis/checkmate/issues/135 would do something very simlar (same?) so I could create a function to avoid duplication.

2021-01-27 12:28 UTC, seanh commented on via/views/view_pdf.py
> +    checkmate = CheckmateClient(request.registry.settings["checkmate_url"])
I think the view is fine.

I'm sure there's some Pyramid thing that could be done where a view can just declare (for example in its `@view_config`) that it wants Checkmate checking, and the check would happen automatically and the view would not even be called if the check failed. But I don't think it's necessary.

We're going to want to add the same Checkmate support to a second view in Via 3 as well (see https://github.com/hypothesis/checkmate/issues/135). At that point it might be worth putting this code into a shared helper function that just returns the `HTTPTemporaryRedirect` or `None`. Or actually doing a fancier Pyramid integration.

2021-01-27 12:28 UTC, seanh commented on via/views/view_pdf.py
> +        logging.exception("Failed to check url against checkmate with error: %s", err)
Do you actually need to pass `err` here? I think `logging.exception()` logs the current exception automatically

2021-01-27 12:28 UTC, seanh commented on via/views/view_pdf.py
> +        logging.exception("Failed to check url against checkmate with error: %s", err)
Yeah, I think "fail open" is the right approach for LMS's private instance of Via 3. Whereas for public Via, I think we want it to crash if calling Checkmate fails

2021-01-27 12:31 UTC, marcospri commented on via/views/view_pdf.py
> +        logging.exception("Failed to check url against checkmate with error: %s", err)
> Do you actually need to pass `err` here? I think `logging.exception()` logs the current exception automatically

I think you are right,, it will create a long message string too, will just remove that part.

@seanh It does by default but can't confirm 100% looking at the pyramid-sentry repo, would `logging.exception` create one in sentry?

2021-01-27 12:48 UTC, seanh commented on via/views/view_pdf.py
> +        logging.exception("Failed to check url against checkmate with error: %s", err)
I _think_ it will due to Sentry's logging integration (which is enabled by default): https://docs.sentry.io/platforms/python/guides/logging/

2021-01-28 10:30 UTC, marcospri commented on via/views/blocker.py
> +def checkmate_block(view, url_param="url", allow_all=True):
Ended up doing a decorator as it was just simpler than a plain function

If this approach works and we use it multiple services we could eventually move it to checkmatelib

2021-01-28 11:05 UTC, seanh commented on via/views/blocker.py
> +def checkmate_block(view, url_param="url", allow_all=True):
Nice. Yeah I agree checkmatelib could provide Pyramid things like view derivers. It could even provide an actual Pyramid extension if that becomes necessary.

I **don't** think you need to change this (the decorator is fine) but just FYI there's a similar Pyramid feature named "view derivers" that can also be useful for doing this sort of thing: https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hooks.html#view-derivers View configs can pass arguments to view derivers, see: https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hooks.html#custom-view-derivers

We have a view deriver in LMS for example: <https://github.com/hypothesis/lms/blob/ac8bbad5c6b96b9fff1ec80adc01d97aedfac7a3/lms/validation/__init__.py#L65-L95> Example of a view using it: <https://github.com/hypothesis/lms/blob/ac8bbad5c6b96b9fff1ec80adc01d97aedfac7a3/lms/views/api/canvas/authorize.py#L78>

2021-01-28 11:36 UTC, marcospri commented on via/views/blocker.py
> +def checkmate_block(view, url_param="url", allow_all=True):
Deriver looks like the pyramid-y way of doing it but it's also very similar so I'd say we can convert it into one once we move it out to checkmatelib or extension.

2021-01-28 12:50 UTC, seanh requested changes
Looks good and I think the view decorator is a nice solution :+1:

Some requests (see comments for details):

- [x] Rename `test_blocker.py` to `blocker_test.py`
- [x] Tweak the `CheckmateClient` fixture to use `patch`
- [x] Move the `CheckmateClient` fixture into `blocker_test.py`
- [x] Change `static_content_test.py` and `view_pdf_test.py` to use `httpretty` instead of the `CheckmateClient` fixture
- [x] Spec the `block` fixture

Stuff that we can probably leave for follow-up PRs:

* functests need to be added to Via 3
* Any tests that use the `test_app` fixture are functional tests, and need to be moved into `tests/functional/`:
  * All of `test_static_content.py`
  * The existing `test_caching_is_disabled()` and your new `test_blocked_by_checkmate()` in `view_pdf_test.py`
  * Anything else that uses `test_app`

2021-01-28 12:50 UTC, seanh commented on tests/unit/conftest.py
> +        yield CheckmateClient
This should use our `patch` fixture, which'll handle the patching and unpatching and autospeccing etc:

```suggestion
@pytest.fixture()
def CheckmateClient(patch):
    return patch("via.views.blocker.CheckmateClient")
```

2021-01-28 12:50 UTC, seanh commented on tests/unit/static_content_test.py
> +        CheckmateClient.return_value.check_url.return_value = None
Oof, this whole file is actually functional tests, and the `test_app` fixture it uses belongs in the functional tests fixtures. Not sure how this happened but we should write a PR to move these out into `tests/functional/`, these aren't unit tests.

I'm not sure what functional tests for Via 3 should do about the fact that Via 3 calls Checkmate. Reaching in to `views/blocker.py` and patching the `CheckmateClient` is one option, but it means this functional test is tied to an implementation detail of `blocker.py`.

Another option would be to use [httpretty](https://httpretty.readthedocs.io/) (which is [already installed in Via 3's tests](https://github.com/hypothesis/checkmate/blob/90a9eec4ee0dbcda85cd33f8ed1a7293d47390dc/tests/unit/conftest.py#L108-L121)) to fake the response from Checkmate:

```suggestion
    def test_immutable_contents(self, test_app):
        import httpretty
        httpretty.register_uri(
            httpretty.GET,
            "http://localhost:9099/api/check",
            status=204,
        )
```

(With the `import httpretty` moved to the top of the file, of course.) This means that we're testing the app in integration with `checkmatelib`, and the test is no longer dependent on `blocker.py` internals. On the other hand, the test now has knowledge of what Checkmate's public API is.

I think the ideal solution here would be for `checkmatelib` to provide test helper functions for app's tests to call. So Via 3's tests would call something like `checkmatelib.allow("example.com")` and that would do whatever is necessary (mocking, registering httpretty URIs, ...) to make `check_url()` response that `"example.com"` is allowed. That way the Checkmate-specific knowledge all lives in checkmatelib. It's probably not worth doing this for now thoughl

2021-01-28 12:50 UTC, seanh commented on tests/unit/static_content_test.py
> +        CheckmateClient.return_value.check_url.return_value = None
The `httpretty.register_uri()` should be done in the `get_salt()` helper below, rather than in the test. The `get_salt()` helper is what actually causes the requests to Checkmate to get sent

2021-01-28 12:50 UTC, seanh commented on tests/unit/conftest.py
> +        yield CheckmateClient
This should be moved into `blocker_test.py` as well, since it's patching a name in `blocker.py`. I don't think tests for _other_ files (like `view_pdf.py`) should patch a name in `blocker.py` since that couples `view_pdf.py`'s tests to internal details of `blocker.py`.

`static_content_test.py` and `view_pdf_test.py` should use `httpretty` instead of this patch, see my other comments.

It's not quite the same thing as you're doing here, but we follow this pattern where `test_foo.py` should _only_ patch names in the corresponding `foo.py` module's namespace, we avoid patching names elsewhere or having global patch fixtures 'cos it can get really confusing. See this comment for why: https://github.com/hypothesis/via3/pull/222#discussion_r469865055

2021-01-28 12:50 UTC, seanh commented on tests/unit/via/views/view_pdf_test.py
> +        CheckmateClient.return_value.check_url.return_value = None
Ugh, the existing test here is a functional test mixed in with the unit tests. It's using `test_app.get(...)` which actually sends a simulated request through the entire app at the WSGI level (it uses [webtest](https://docs.pylonsproject.org/projects/webtest/en/latest/)), so it's running the entire Via 3 app and Pyramid and everything. That's a functional test, not a unit test for the view.

I think it should use `httpretty` rather than mocking `CheckmateClient`, same as I commented on `static_content_test.py`.

And like `static_content_test.py` we should send a follow-up PR to move it out into `tests/functional/` because it's not a unit test.

2021-01-28 12:50 UTC, seanh commented on tests/unit/via/views/view_pdf_test.py
> +        assert response.location == block.presentation_url
This is a functional test so it doesn't belong here. I can see that you were following the example of the existing ` test_caching_is_disabled()` above but unfortunately that test is wrong. Options:

1. Just don't test this. We have unit tests for the `checkmate_block()` view decorator. Applying the view decorator to the view is purely declarative, it's just `@view_config(..., decorator=checkmate_block)`, so we don't need to test that.

2. If you _do_ want to test it add a functional test in `tests/functional/` for it. That would basically be the same test as you've added here but in `tests/functional/`, and I think it'd use `httpretty` to set up Checkmate's response rather than mocking `CheckmateClient`.

A view's configuration (whatever is declared in its `@view_config`) isn't part of what that view's unit tests cover. For example one of the things in view config is `route_name="foo"` and other predicates the decide when that view is called and when it isn't. But the view's unit tests don't include a test that _"When a `GET` request is sent to `/pdf/` it calls the `view_pdf` view"_. Similarly `renderer="json"` in a `@view_config` will turn the view's reponse into JSON (serializing a dict that the view returns into a JSON string, setting the Content-Type header to application/json, ...) but we don't write view unit tests for that. If we wanted to test these things we'd write functional tests.

2021-01-28 12:50 UTC, seanh commented on tests/unit/via/views/test_blocker.py
> +    @pytest.fixture()
```suggestion
    @pytest.fixture
```

2021-01-28 12:50 UTC, seanh commented on tests/unit/via/views/test_blocker.py
> +from unittest.mock import Mock
Should be renamed to `blocker_test.py` (we put the `_test` on the end because that works better with autocompletion)

2021-01-28 12:50 UTC, seanh commented on tests/unit/via/views/test_blocker.py
> +        return Mock(presentation_url="http://checkmate/blocked")
I think this is a mock of checkmatelib's `BlockResponse`? If so, might want to autospec it:

```python
return mock.create_autospec(checkmatelib.client.BlockResponse, instance=True, spec_set=True)
```

The reason is that the mock will catch breakage if checkmatelib's interface changes.

It looks to me like `BlockResponse` is public in checkmatelib (since `checkmatelib.CheckmateClient.check_url()` returns them) so I think checkmatelib should expose `BlockResponse` in its `__init__.py` as it does for `CheckmateClient` and `CheckmateException`: https://github.com/hypothesis/checkmatelib/blob/6b94ebff539d28e919b939841372d7453aae3ac4/src/checkmatelib/__init__.py. Then it'd just be `create_autospec(checkmatelib.BlockResponse, ...)`.

If we can't autospec this mock we should at least manually spec it (see <https://www.seanh.cc/2017/03/17/the-problem-with-mocks/#passing-a-list-of-strings-to-spec_set>), unspecced mocks are dangerous 'cos they'll respond successfully to any method call.

2021-01-28 12:52 UTC, seanh commented on tests/unit/via/views/test_blocker.py
> +        return Mock(presentation_url="http://checkmate/blocked")
Probably rename the fixture to `block_response` as well, following the `BlockResponse` class's name

2021-01-28 16:53 UTC, seanh approved these changes
Looks good :+1: I suggested some minor changes but let's get this one merged.

We need to add the `CHECKMATE_URL` envvar to QA and prod before deploying it, right?

And we can test it on QA by making sure that:

1. A blocklisted domain is blocked. For example this <https://qa-via3.hypothes.is/pdf?url=https://vimeo.com/> should be blocked (currently it is not blocked and loads PDF.js, but that fails because vimeo.com isn't a PDF file)

2. A non-blockedlisted domain is not blocked. E.g. https://qa-via3.hypothes.is/pdf?url=https://h.readthedocs.io/_/downloads/en/latest/pdf/

And test that our QA test assignments in Canvas still work

2021-01-28 16:53 UTC, seanh commented on via/views/blocker.py
> +"""Helper view decorators to integrate with checkmate's API."""
```suggestion
"""View decorators to integrate with checkmate's API."""
```

2021-01-28 16:53 UTC, seanh commented on via/views/blocker.py
> +
```suggestion
```

2021-01-28 16:53 UTC, seanh commented on tests/unit/via/views/view_pdf_test.py
> +    @httpretty.activate
```suggestion
```

I think this is unnecessary? We have a global pytest fixture that activates it for every test

2021-01-28 16:53 UTC, seanh commented on tests/unit/via/views/view_pdf_test.py
> +    @httpretty.activate
```suggestion
```

2021-01-28 17:08 UTC, jon-betts commented on via/views/blocker.py
> +def checkmate_block(view, url_param="url", allow_all=True):
A smattering of helpers and things seems like a good thing to include

2021-01-29 11:19 UTC, merged