Enable checkmate checks on route_by_content
hypothesis/via3 pull request #352
Opened 2021-02-05 10:18 UTC by marcospri

Won't have any effect until `CHECKMATE_ENABLED` is enabled again.

2021-02-08 16:57 UTC, jon-betts requested changes
This all looks pretty much fine, but I think we should follow the style elsewhere for fixtures which setup a situation, and use `@pytest.mark.usefixture`

It looks like it's gone out in a different PR, but the view decorator here doesn't seem follow our standard pattern for naming things in the views. I'd expect this to be a view, rather than contain tools for views. Not sure if this is something we want to fix here or not. I'm surprised this didn't get any comment at the time, but maybe I was asleep at the wheel.

2021-02-08 16:57 UTC, jon-betts commented on tests/conftest.py
> +    get_url_details.return_value = ("application/html", 200)
I'm not sure re-use here is the right play. It makes the relevant test very short, but it's also quite mysterious. We have a fixture we don't use or declare.

This might be a good example where repeating yourself locally is actually better? I'm not sure.

I'd say I just about side with you on this one. There's enough stuff here and we use it twice...

2021-02-08 16:57 UTC, jon-betts commented on via/views/route_by_content/view.py
> +from via.views.blocker import checkmate_block
This confused me on first read. On the whole, unless otherwise stated most things in `product.views.` are a view. The exception so far being `exceptions.py` which is a mixed bag. Either it's exceptions related to the views (which I prefer in the parent, but opinion varies), or pyramid exception views.

We are branching out with directories for views when they contain lots of local classes. That wouldn't work here as it's intended to be shared.

I wonder if this would be better as `_decorators.py `or something so you have from `via.views._decorators import checkmate_block`, which heavily suggests it's not a view itself?

2021-02-08 16:57 UTC, jon-betts commented on tests/functional/api/view_route_by_content_test.py
> +    def test_proxy_html(self, test_app, html_response):
```suggestion
    @pytest.mark.usefixtures("html_response")
    def test_proxy_html(self, test_app):
```

We normally use mark when we have fixtures that setup a situation rather than return a value. In fact, we intentionally _don't_ return a value in fixtures where we are trying to setup a situation, to help you tell the fact by looking at the fixture definition (no return value = pure side effect fixture)

This helps in a few ways:

 * It's a bit baffling if you look at the code and think "This arg isn't used, I'll remove it" then the test breaks
 * The value is just None, so if you debug, it's not clear why this happened

2021-02-08 16:57 UTC, jon-betts commented on tests/functional/api/view_route_by_content_test.py
> +    def test_proxy_pdf(self, test_app, pdf_response):
```suggestion
    @pytest.mark.usefixtures("pdf_response")
    def test_proxy_pdf(self, test_app):
```

Ditto

2021-02-09 10:13 UTC, marcospri commented on via/views/route_by_content/view.py
> +from via.views.blocker import checkmate_block
Changed it to `decorators.py` (which we could break further if it grows too much)

2021-02-09 10:15 UTC, marcospri commented on tests/conftest.py
> +    get_url_details.return_value = ("application/html", 200)
Not sure either, I think the name it's relatively self explanatory so having them in conftest it's not too confusing.

2021-02-09 14:37 UTC, seanh requested changes

2021-02-09 14:37 UTC, seanh commented on tests/unit/via/views/blocker_test.py
> -from via.views.blocker import checkmate_block
Does this file need to be renamed to `decorators_test.py` as well?

2021-02-09 14:37 UTC, seanh commented on tests/conftest.py
> +    get_url_details.return_value = ("application/html", 200)
It looks like you moved these three fixtures into `tests/conftest.py` because your functional test (in `view_route_by_content_test.py`) needs to use them. But I think a functional test should probably work by faking the third-party server's response using `httpretty`, rather than by patching part of the code. Having functional tests use patch fixtures seems too brittle.

Then you won't need to move `patch` and `autopatcher`, those can go back into `tests/unit/conftest.py`

2021-02-09 14:37 UTC, seanh commented on tests/functional/api/view_route_by_content_test.py
> +        )
I think you should move the `html_response` and `pdf_response` fixtures into this test class, and they should work by setting up `httpretty` so that requests to `http://example.com` respond with the required content-type headers

2021-02-10 16:50 UTC, jon-betts commented on tests/functional/api/view_route_by_content_test.py
> +        )
FYI, we stopped needing them in the place they originally came from in https://github.com/hypothesis/via3/pull/369, so this actually won't even be duplication.

2021-02-11 14:29 UTC, seanh approved these changes

2021-02-11 14:29 UTC, seanh commented on tests/functional/api/view_route_by_content_test.py
> +from urllib.parse import quote_plus
I wonder if the file should by `views/route_by_content_test.py` or just `route_by_content_test.py`, rather than `view_route_by_content_test.py`

2021-02-12 13:28 UTC, merged