Remove checkmate_enabled flag
hypothesis/via3 pull request #402
Opened 2021-03-02 10:59 UTC by marcospri

Waiting for CHECKMATE_ENABLE to be set to `1` on prod before deploying.

2021-03-02 11:27 UTC, seanh requested changes

2021-03-02 11:27 UTC, seanh commented on tests/functional/conftest.py
> +        body="""{"data": []}""",
```suggestion
        body=None,
```

Checkmate's 204 responses actually have no body

2021-03-02 11:27 UTC, seanh commented on tests/unit/via/views/route_by_content_test.py
> -        )
Did you mean to delete this one? It should still pass `blocked_for` to Via right?

2021-03-02 11:33 UTC, marcospri commented on tests/unit/via/views/route_by_content_test.py
> -        )
Not sure, if a checkmate check already happen do we need to pass that to viahtml? That was my original thinking

2021-03-08 10:18 UTC, seanh commented on tests/unit/via/views/route_by_content_test.py
> -        )
Hmm. Does Via HTML still do a Checkmate check? I think when Via 3 redirects to Via HTML, Via HTML still does its own Checkmate check in which case, in theory, the request could pass Via 3's check but get blocked by Via HTML's one (for example if Via 3 fails to reach Checkmate so allows the request through, but then Via HTML succeeds in reaching Checkmate). So I think Via HTML could still generate a Checkmate block page, so it needs the `blocked_for` param.

It does seem like there's a simple optimisation we could do in Via HTML here though: when it sees (from `Referer`) that the request came from Via 3 (or from LMS, which is what I think `Referer` will refer to) it can just trust it and skip any Checkmate check

2021-03-08 10:18 UTC, seanh approved these changes

2021-03-08 10:21 UTC, seanh commented on tests/unit/via/views/route_by_content_test.py
> -        )
One issue with Via HTML skipping its Checkmate check if the `Referer` is LMS is that it'd allow `curl` requests that send `Referer: lms.hypothes.is` to skip the blocklist. Currently scripts can bypass the LMS-only lockdown and the allow-list by just sending the appropriate `Referer` header, but at least they can't skip the blocklist that way

2021-03-16 09:18 UTC, merged